
name: Move labeled issue to waiting

on:
  issues:
    types: [labeled]

jobs:
  automate-project-columns:
    if: ${{ contains(github.event.issue.labels, 'will close automatically') }}
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.7.1
        with:
          project: test-action
          column: waiting
          repo-token: ${{ secrets.ACCESS_TOKEN }}
